EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: Prod
      Version: "1.20"
      RoleArn: "arn:aws:ec2:ap-northeast-3:882956824445:subnet/subnet-00626085943e16ca8"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-06972dc949046a566
        SubnetIds:
          - subnet-00626085943e16ca8
          - subnet-006b1fc287cebe411
        EndpointPublicAccess: false
        EndpointPrivateAccess: true
        PublicAccessCidrs: [ "1.1.1.2/32" ]
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
      Tags:
        - Key: "key"
          Value: "val"
